### ISSUE TITLE
Custom markers for GUI-tests

### ISSUE THREAD

**Issue by The-Compiler** [hackebrot/qutebrowser#15]
Would it make sense to use [a custom marker](http://pytest.org/latest/example/markers.html) for GUI-tests, e.g. #9?

Then I could for example skip GUI tests when I don't have X available or don't want random windows popping up.

**Comment by nicoddemus** [comment]
Sure... in fact, we can automatically add a custom marker (say, `gui`?) to all tests that use a `qtbot` fixture. :smile:

So you can execute all non-GUI tests with:

```
py.test -m "not gui"
```

I will get on this later then.

**Comment by nicoddemus** [comment]
Sample output:

```
$ py.test -m "gui"
============================= test session starts =============================
platform win32 -- Python 3.4.2 -- py-1.4.26 -- pytest-2.7.0
qt-api: pyqt5
rootdir: X:\qutebrowser, inifile: tox.ini
plugins: qt, capturelog, mock
collected 1071 items

tests\mainwindow\statusbar\test_percentage.py .....
tests\mainwindow\statusbar\test_progress.py ......
tests\mainwindow\statusbar\test_textbase.py ....

===================== 1056 tests deselected by "-m 'gui'" =====================
=========== 15 passed, 1056 deselected, 3 warnings in 2.33 seconds ============
```
