### ISSUE TITLE
Segfaults since merging layout branch

### ISSUE THREAD

**Issue by The-Compiler** [hackebrot/qutebrowser#22]
Since merging #16 I occasionally see segfaults when the tests are finished and `pytest` is exiting.

I've seen that before switching to pytest on the Windows builder, but very rarely. Now I mainly see it on the Debian/Ubuntu builders all ~10 builds or so.

From dmesg:

```
[Apr11 13:24] QXcbEventReader[2682]: segfault at 7f711e8ca029 ip 00007f711e8ca029 sp 00007f711beb7ee0 error 14
[Apr13 07:49] Qt bearer threa[5141]: segfault at 7fce761cfa50 ip 00007fce82c8b30c sp 00007fce76e146e0 error 4 in libQt5Network.so.5.3.2[7fce82bed000+151000]
```

Example output: [stdout](http://qutebrowser.org:8010/builders/debian-jessie/builds/428/steps/unittests/logs/stdio)

Any idea what's going on there? I've tried to run `tox -e unittests` on that builder in an endless loop without buildbot for two hours and didn't get any segfaults...

I've now reconfigured buildbot to use [catchsegv](http://man.he.net/man1/catchsegv) on any tox-command on Linux in the hope to find out more.

**Comment by The-Compiler** [comment]
Just got one on the two Ubuntu builders simultaneously...

The Ubuntu trusty one [only shows a register dump](http://qutebrowser.org:8010/builders/ubuntu-trusty/builds/429/steps/unittests/logs/stdio), but the Ubuntu Utopic one [has a stacktrace](http://qutebrowser.org:8010/builders/ubuntu-utopic/builds/432/steps/unittests/logs/stdio). Demangled:

```
/usr/lib/x86_64-linux-gnu/libQt5Network.so.5(QNetworkConfigurationManagerPrivate::pollEngines() 0xdc)[0x7f9bdf3482fc]
/usr/lib/x86_64-linux-gnu/libQt5Network.so.5( 0x10c0dd)[0x7f9bdf3b60dd]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QMetaObject::activate(QObject*, int, int, void**) 0x77d)[0x7f9be820e27d]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QTimer::timerEvent(QTimerEvent*) 0x28)[0x7f9be821ba08]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QObject::event(QEvent*) 0xb3)[0x7f9be820f0e3]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x8c)[0x7f9be0b1f16c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(QApplication::notify(QObject*, QEvent*) 0x3fe)[0x7f9be0b2441e]
/home/buildbotx/slaves/slave/ubuntu-utopic/build/.tox/unittests/lib/python3.4/site-packages/PyQt5/QtWidgets.cpython-34m-x86_64-linux-gnu.so( 0x27e286)[0x7f9bdfe85286]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QCoreApplication::notifyInternal(QObject*, QEvent*) 0xdb)[0x7f9be81df81b]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QTimerInfoList::activateTimers() 0x545)[0x7f9be8235d85]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5( 0x32d1b1)[0x7f9be82361b1]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch 0x24d)[0x7f9be71a5c5d]
/lib/x86_64-linux-gnu/libglib-2.0.so.0( 0x49f48)[0x7f9be71a5f48]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration 0x2c)[0x7f9be71a5ffc]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x57)[0x7f9be8236e57]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x112)[0x7f9be81dd042]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(QThread::exec() 0xb4)[0x7f9be7fa14a4]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5( 0x9d2ee)[0x7f9be7fa62ee]
/lib/x86_64-linux-gnu/libpthread.so.0( 0x80a5)[0x7f9bebc640a5]
/lib/x86_64-linux-gnu/libc.so.6(clone 0x6d)[0x7f9beb991cfd]
```

**Comment by nicoddemus** [comment]
Ouch, that's unfortunate. :disappointed: 

Are you running #23 in your C.I.? How is that faring?

**Comment by The-Compiler** [comment]
Got the first segfault just after pushing the merge...

I wonder if https://github.com/pytest-dev/pytest-qt/pull/38 will help though. @nicoddemus, are you planning a new release with that?

**Comment by nicoddemus** [comment]
Can we use `pytest-qt` directly from source, just to check if the change in [pytest-dev/pytest-qt#38](https://github.com/pytest-dev/pytest-qt/pull/38) solves this problem?

**Comment by The-Compiler** [comment]
Sure, I did so in https://github.com/The-Compiler/qutebrowser/commit/71608af4867f61b7bb9e22318680c78383d793fc - now give me a few days to see if there still are segfaults :smile:

**Comment by nicoddemus** [comment]
:pray:

**Comment by The-Compiler** [comment]
Unfortunately it doesn't, I still get a segfault at the same place (`QNetworkConfigurationManagerPrivate::pollEngines()`). :cry:

**Comment by nicoddemus** [comment]
:cry: 

I will try to reproduce this on Windows during the weekend and hopefully work on a solution or workaround.

I suspect the crash has to do with the fact that we are calling `QApplication.exit()` **and/or** the variable which holds the `QApplication` instance is being garbage collected too early in the `qapp` fixture:

``` python
# pytestqt.plugin
@pytest.yield_fixture(scope='session')
def qapp():
    """
    fixture that instantiates the QApplication instance that will be used by
    the tests.
    """
    app = QApplication.instance()
    if app is None:
        app = QApplication([])
        yield app
        app.exit()
    else:
        yield app  # pragma: no cover
```

@The-Compiler, meanwhile can you try create a global `QApplication` in your conftest file?

``` python

global_qapp = QApplication([])

@pytest.fixture(scope='session', autouse=True)
def app_and_logging(qapp):
    assert qapp is QApplication.instance()  # just as a sanity check
```

This will prevent it from being garbage collector up until the interpreter is actually shutting down. If the crashing stops, this might be a clue about what's happening and how to fix it.

All in all, `QApplication` singleton implementation has a few weird quirks:

``` python
>>> from PyQt5.QtWidgets import QApplication, qApp
>>> print(QApplication.instance())
None
>>> qApp
<PyQt5.QtWidgets.QApplication object at 0x02A89B20>   # huh?
>>> x = QApplication([])
<PyQt5.QtWidgets.QApplication object at 0x02A89B70>
>>> x is qApp
False
```

**Comment by nicoddemus** [comment]
I added this line in `conftest.py` on my computer:

``` python
def pytest_collection_modifyitems(items):
    ...
    items[:] = items * 100
```

Which will make the suite run repeatedly 100 times, but no crash at all: :disappointed: 

```
=== 143400 passed, 800 skipped, 2500 xfailed, 3 warnings in 385.00 seconds ====
```

**Comment by The-Compiler** [comment]
Note the segfault actually happens when pytest exits, after printing the summary - so if you can reproduce it, likely you'll have to write something like this to run it repeatedly:

``` python
import subprocess
for _ in range(100):
    subprocess.check_call(['tox', '-e', 'unittests'])
```

**Comment by nicoddemus** [comment]
Good point, will try that later!

**Comment by The-Compiler** [comment]
Gaaaah, this is so weird.

When trying the script twice (because I also added a print for the count) I got the segfault after <5 tries both times, and now it's running for 200 tries or so without issues...

**Comment by nicoddemus** [comment]
Did you try to create the global `QApplication` I mentioned earlier, or do you mean the script for running the suite repeatedly?

**Comment by nicoddemus** [comment]
Just ran your script for 80 times now, no segfault... :sweat:

**Comment by The-Compiler** [comment]
I've now run it with a simple bash-loop instead of a loop implemented in python via subprocess - I did run it in two VMs (Ubuntu Trusty/Utopic) and it took 2500/1800 iterations to crash...

I'll now play a bit with calling it from the python script again in the hope to find a more or less reproducible way to crash it, and then I'll try your workaround from above.

If that doesn't help I'll also try to post to the PyQt mailinglist and see if someone has an idea there.

**Comment by nicoddemus** [comment]
Thanks for the follow up, please keep us posted. 

I actually have good hopes regarding my workaround, let's see. :pray:

**Comment by The-Compiler** [comment]
Nope, just got another QXcbEventReader segfault - though at least the Qt Bearer Thread ones seem to be gone.

Though that seems to be a [common](http://python.6.x6.nabble.com/PyQt5-segfault-when-closing-a-QMainWindow-td5026465.html) [issue](http://python.6.x6.nabble.com/Application-crash-on-exit-under-Linux-td5067510.html) with PyQt...

A proposed solution in one of those threads:

> del the app object explicitly before calling exit() and your program wont
> crash. Simpolarly if it has a main window del that explicitly before
> deleting the app object.

Though I don't really see where that'd apply here...

**Comment by nicoddemus** [comment]
> Nope, just got another QXcbEventReader segfault - though at least the Qt Bearer Thread ones seem to be gone.

Just to be clear, that crash happened with the workaround of keeping a global `QApplication` instance applied?

It is disappointing how easy is to crash PyQt. :disappointed: 

I will build a VM myself to try join you in the testing efforts, I have a few ideas I can try.

Cheers, :beers:

**Comment by The-Compiler** [comment]
> Just to be clear, that crash happened with the workaround of keeping a global `QApplication` instance applied?

Yep:

``` diff
diff --git a/tests/conftest.py b/tests/conftest.py
index 892a919..c42388f 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -24,6 +24,10 @@ import itertools

 import pytest

+from PyQt5.QtWidgets import QApplication
+
+global_qapp = QApplication([])
+

 @pytest.fixture(scope='session', autouse=True)
 def app_and_logging(qapp):
@@ -33,6 +37,7 @@ def app_and_logging(qapp):
     """
     from log import init
     init()
+    assert qapp is QApplication.instance()     


 @pytest.fixture(scope='session')
```

> It is disappointing how easy is to crash PyQt. :disappointed: 

Indeed... I love PyQt otherwise, but this really makes me think "damn, I should've learned C++ instead..." sometimes.

> I will build a VM myself to try join you in the testing efforts, I have a few ideas I can try.

Thanks! I'm testing with a more-or-less vanilla Ubuntu Trusty/Utopic.

**Comment by nicoddemus** [comment]
Just ran the test suite `720` times in an Ubuntu box created by Vagrant and using `Xvfb`, still no crash. :disappointed: 

I will let it running the entire night to see if it crashes.

**Comment by The-Compiler** [comment]
If it helps I can give you an SSH account to the VM I see the crashes in - I can just do a snapshot first so you can do whatever you want.

Just give me your SSH public key (on Windows, you can for example use [PuTTY](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html) and PuTTYgen to generate the key).

**Comment by nicoddemus** [comment]
That would help, specially if I can edit `qutebrowser` to try a few ideas.

Here's my public key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArLJSvvDK3YAUr0yU3qDhwTqDriqORnqgr2TZG0TLXq59qaBLMqGaYj23KhHDkJmMFgCxtwYcLdXkH1QxILbP2i1HJIQOoVbMZP+S0YE8G2T7ZcaNJnwS3eURtR5qa6K1/U3AfnHIyR6WSQE3X1PLZcApaC8pvAXR12lvZCAsBlj3yyajwYHJ06N3+B+RgcPvpSw2h1BWdccWWZssZm8MNF/AqZknbtIeLr0LQc+/cGROorsSQzQlc1QhVA74KrEL3AzzH6EWrmmbUlRd84D8TGzG+REmfJ2Hz/GfIkYfE3Cle8vfqLfEMHZd7A429lghc/3x26nTqd3StHFAKtuTrQ== bruno@FLDEVWS001
```

How many tries are you usually seeing until a crash?

**Comment by The-Compiler** [comment]
Okay, you should be able to connect to nicoddemus@the-compiler.org port 2325.

I already cloned qutebrowser to your homedir and inside that folder there's a repeat.py I use to test.

It's hard to say how many tries it'll take... When I ran the script now, it segfaulted on the first try, other times it took dozens or hundreds of tries.

**Comment by nicoddemus** [comment]
Thanks for setting it up. I'm timing out when trying to connect from work though, I will test this later from home.

If it is failing after a few dozen or hundred times that's OK... my VM spent the entire night (over 7200 tries) and no crash. :disappointed:

**Comment by nicoddemus** [comment]
Hi @The-Compiler,

I can connect to the server, but it fails to authenticate:

```
$ ssh nicoddemus@the-compiler.org -p 2325
nicoddemus@the-compiler.org's password:
Permission denied, please try again.
nicoddemus@the-compiler.org's password:
Permission denied, please try again.
nicoddemus@the-compiler.org's password:
Permission denied (publickey,password).

$ cat %HOME%/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArLJSvvDK3YAUr0yU3qDhwTqDriqORnqgr2TZG0TLXq59qaBLMqGaYj23KhHDkJmMFgCxtwYcLdXkH1QxILbP2i1HJIQOoVbMZP
+S0YE8G2T7ZcaNJnwS3eURtR5qa6K1/U3AfnHIyR6WSQE3X1PLZcApaC8pvAXR12lvZCAsBlj3yyajwYHJ06N3+B+RgcPvpSw2h1BWdccWWZssZm8MNF/AqZknbtIeLr0LQc+/
cGROorsSQzQlc1QhVA74KrEL3AzzH6EWrmmbUlRd84D8TGzG+REmfJ2Hz/GfIkYfE3Cle8vfqLfEMHZd7A429lghc/3x26nTqd3StHFAKtuTrQ== bruno@FLDEVWS001
```

**Comment by The-Compiler** [comment]
Whoops, seems I copied the key with linewraps and didn't notice - should work now.

**Comment by nicoddemus** [comment]
Working now, thanks!

**Comment by nicoddemus** [comment]
I'm still investigating, but after a lot of tests I found that removing two test files from the test suite and it no longer crashes:

```
tests/mainwindow/statusbar/test_progress.py
tests/mainwindow/statusbar/test_textbase.py
```

I will continue the investigation and try to find a single test from those files which reproduces the crash when ran continuously
.

**Comment by The-Compiler** [comment]
For the `QNetworkConfigurationManagerPrivate::pollEngines()` (which I still see with the code in my current master - this time 3/4 VMs segfaulted at the same time) issue, I found [QTBUG-44407](https://bugreports.qt.io/browse/QTBUG-44407).

There the reporter says:

> I'm sorry. this problem was QNetworkConfigurationManager wasn't destroyed.

However we don't use a `QNetworkConfigurationManager` directly, so I wonder how that advice helps...

**Comment by nicoddemus** [comment]
Update:

I noticed that for [tests/mainwindow/statusbar/test_progress.py](https://github.com/The-Compiler/qutebrowser/blob/master/tests/mainwindow/statusbar/test_progress.py), the test which causes the crash is `test_load_started`; `test_tab_changed` does not cause the crash if ran continuously.

I'm running out of ideas, but a possible temporary solution is to `xfail` the tests which cause the crash:

``` python
@pytest.mark.xfail(reason='crashing', run=False)
def test_load_started(progress_widget):
```

At least until we have a better idea of what to do. :frowning:

**Comment by The-Compiler** [comment]
Hah, weird... I haven't applied the fix yet, but I haven't seen any segfaults since the 19th... I wonder if some update somehow resolved it.

Closing this for now, and then let's hope it never comes up again :wink:

**Comment by nicoddemus** [comment]
:pray: :smile:

**Comment by The-Compiler** [comment]
Nope, still getting segfaults. :worried:

I'll test disabling `test_load_started` next.

**Comment by nicoddemus** [comment]
Bummer. :cry:

**Comment by The-Compiler** [comment]
Disabling that test didn't help. I wonder if the pytest-qt update helps somehow. We'll see.

**Comment by hackebrot** [comment]
I'm afraid this is still a problem? :worried:

**Comment by The-Compiler** [comment]
I've not seen it in a while - though I upgraded the Ubuntu Utopic VM to Vivid (the next version). But I'd still expect it to happen on the Ubuntu Trusty VM... Let's wait and see if it still happens in the next few weeks.

**Comment by The-Compiler** [comment]
I think it's more than time to close this :laughing:

**Comment by hackebrot** [comment]
@The-Compiler haha 😹
