### ISSUE TITLE
Way forward after adopt pytest month

### ISSUE THREAD

**Issue by The-Compiler** [hackebrot/qutebrowser#26]
Just wanted to do a little wrap-up as April is over already :cry:

But I definitely got a good idea about how pytest works! I feel capable of rewriting/cleaning up the remaining existing tests, and adding new tests definitely is easier than it was before!

For #22 (segfaults), @nicoddemus is currently investigating on my server, but it already seems a bit better, and the segfaults which are remaining might as well be a PyQt issue...

For #8 (getting rid of logging), @nicoddemus is working on capturing Qt logging in https://github.com/pytest-dev/pytest-qt/pull/40 and I plan to contribute the missing parts to `pytest-catchlog` here: https://github.com/eisensheng/pytest-catchlog/issues/1 - the aim at the end is to show tests as "finished with warnings" in my CI when there's unexpected log/Qt output but the tests succeeded.

@hackebrot / @nicoddemus - is there anything else in progress I'm unaware of so far?

If you guys are done otherwise I'll do some more reorganisation/cleanup in the coming weeks - thank you very much for the pytest kickstart and all the contributions!

**Comment by nicoddemus** [comment]
As for Qt logging capturing, things are going smoothly but I'm waiting your comments on my last proposal in pytest-dev/pytest-qt#39 before moving forward with that. :smile:

From my part there's nothing in progress other than what was commented. I'm also available for reviewing any future pytest related stuff in qutebrowser.

@hackebrot and @The-Compiler it was really a pleasure working with you guys! Hopefully we will be able to collaborate in future projects as well. :smile:

Cheers, :beers:

**Comment by The-Compiler** [comment]
@nicoddemus Whoops - missed that, sorry! Will look at it tomorrow.

**Comment by hackebrot** [comment]
Hi @The-Compiler @nicoddemus 

Apologies for the late reply. :worried: I am currently busy with my day job as well as my EuroPython talk on [Cookiecutter](https://github.com/audreyr/cookiecutter).

I actually started with more tests of the `utils` subpackage few weeks back however I didn't do much progress.

Florian and Bruno - it was a pleasure working with you and I will be happy to continue on doing so in the future. :bow: :bow: Feel free to ping me if you would like to collaborate :smile_cat:

**Comment by The-Compiler** [comment]
Closing this as everything seems to be taken care of - thanks again to both of you for everything!

**Comment by hackebrot** [comment]
It was great fun! :blush:

**Comment by nicoddemus** [comment]
Ditto! :smile:
