### ISSUE TITLE
GUI tests

### ISSUE THREAD

**Issue by nicoddemus** [hackebrot/qutebrowser#3]
As mentioned in this [comment](https://github.com/The-Compiler/qutebrowser/issues/550#issuecomment-87840262), this are some good places to start:

> For the GUI testing, I think the statusbar widgets would be a good start. textbase.py, percentage.py 
> and progress.py are very simple, text.py and url.py do a bit more, and the others are more complex.

**Comment by nicoddemus** [comment]
Hi @hackebrot,

A little report before going to bed, as I think you will read this in a few hours:

At the moment I'm working on porting pytest-qt to PyQt5. The port is done in [this branch](https://github.com/pytest-dev/pytest-qt/tree/pyqt5), but I want a little more time to fix the travis build to also test against PyQt5. My plan is to release 1.3.0 tomorrow, and start working on some GUI tests on Wednesday, if that's OK with you. :smile:

Cheers, :beers:

**Comment by The-Compiler** [comment]
I think this can be closed.

**Comment by nicoddemus** [comment]
Sure thing. @The-Compiler, please feel free to add me to review new GUI tests that you write (if you want me to, of course). :smile:
