### ISSUE TITLE
monkeypatch/pytest-mock

### ISSUE THREAD

**Issue by nicoddemus** [hackebrot/qutebrowser#5]
Check for opportunities to use `monkeypatch` or `pytest-mock`.

**Comment by The-Compiler** [comment]
I just found this repo :smile:

Currently I'm using [unittest.mock.patch](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) for most patching, and some mocks (from `unittest.mock`) here and there.

I think replacing `unittest.mock.patch` with `monkeypatch` might make sense (as `unittest.mock.patch` is rather... weird sometimes), but I think I'd prefer to continue using `unittest.mock` with pytest (assuming `pytest-mock` is just a thin wrapper over the PyPI [mock](https://pypi.python.org/pypi/mock/)) - in IRC (`#python`) we recently found out the PyPI mock seems to lag behind unittest.mock - example:

``` python
>>> from unittest import mock
>>> mock.mock_open(read_data='foo\nbar\n')('foo.ini').readlines()
['foo\n', 'bar\n']
```

``` python
>>> import mock
>>> mock.mock_open(read_data='foo\nbar\n')('foo.ini').readlines()
<MagicMock name='open().readlines()' id='140406498469088'>
```

**Comment by nicoddemus** [comment]
Hi @The-Compiler! 

Weird, I would assume `unittest.mock` would lag behind `mock`, not the other way around, with Python releases being more sparse than a custom package and all. Oh well.

FYI, pytest-mock is in fact just a thin wrapper, and will prefer to use `unittest.mock` in Python 3.3+, as can be seen [here](https://github.com/pytest-dev/pytest-mock/blob/master/pytest_mock.py#L6).

Cheers, :beers:

BTW, nice that you are looking at the issues we've been creating here. Please feel free to create others or comment on them, like you just did. Your feedback is most welcome! :smile:

**Comment by hackebrot** [comment]
Hey there @The-Compiler :wave: 

We thought it may be a good idea to have this fork for us to prepare our PRs to **qutebrowser** to ease the move for you and the team. In other words we will try to provide some extra information on the concepts of `pytest` as we go but leave out the discussion of @nicoddemus and me.

What's your opinion on this? :relaxed: 

As Bruno already mentioned, please feel free to participate at any time! :bow:

**Comment by The-Compiler** [comment]
I'm perfectly happy with this! I agree it makes sense to have a separate repo to be able to open issues related to pytest without "cluttering" the main repo or having everything in one issue.

PRs are perfect, that's how I imagined this working anyways :)

And yeah, I'm watching this repo and will participate where I can!

**Comment by nicoddemus** [comment]
Just to add a little to the subject of the PRs, we are planning to open the PRs so they will target our fork's `master` instead the original `qutebrowser` repository, so you can merge the PRs into **our** fork once you are happy with what the PR produces. This way you can eventually merge into your repository in your own time. :smile:

**Comment by nicoddemus** [comment]
As we discussed, we will prefer `monkeypatch` and `pytest-mock` as we go along converting tests, so I'm closing this for now. :smile:

**Comment by hackebrot** [comment]
Cool :smile:
